---
 - name: install rvm
   sudo: yes
   apt: pkg={{item}} state=present
   with_items:
    - curl
    - bison
    - openssl
    - libssl-dev
    - libreadline5
    - libreadline-dev
    - libcurl4-openssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libgdbm-dev
    - libncurses5-dev
    - libtool
    - libffi-dev

 - name: download rvm
   command: /usr/bin/curl -L get.rvm.io | bash -s stable

 - name: load rvm
   command: source ~/.rvm/script/rvm
